channels:
  - conda-forge
dependencies:
  - python ==3.12
  - ndv ==0.2.1
  - jupyter ==1.1.1
  - jupyter-rfb ==0.4.4
  - ipywidgets ==8.1.5
  - pyglfw ==2.8.0
  - pyopengl ==3.1.6
  - vispy ==0.14.3
  - pygfx ==0.7.0

